name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:
  
    env:
      BUILD_CONFIG: 'Release'
      PROJECT: 'src/NApprise/NApprise.csproj'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Fetch tags
      run: git fetch --all --tags

    - name: Init submodule
      run: git submodule init && git submodule update
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore $PROJECT
      
    - name: Build
      run: dotnet build $PROJECT --configuration $BUILD_CONFIG --no-restore

    - name: Publish NuGet
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
